# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-20 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paydetail',
            options={'verbose_name': '付款明细', 'verbose_name_plural': '付款明细'},
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(null=True, verbose_name='收件地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='收件人联系方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='reciever',
            field=models.CharField(max_length=100, null=True, verbose_name='收件人'),
        ),
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='订单备注'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='series_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='产品系列号'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='价格'),
        ),
    ]
