# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-20 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180620_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeDic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='显示值')),
                ('code', models.CharField(max_length=100, verbose_name='编码')),
                ('type', models.CharField(max_length=100, verbose_name='字典类型')),
                ('order', models.IntegerField(verbose_name='排序')),
            ],
            options={
                'verbose_name_plural': '一个字典',
                'verbose_name': '一个字典',
            },
        ),
    ]
