# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-24 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180621_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '销售报表', 'verbose_name_plural': '销售报表'},
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order_num',
        ),
        migrations.RemoveField(
            model_name='paydetail',
            name='order_num',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paydetail',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_source',
            field=models.CharField(max_length=100, null=True, verbose_name='销售渠道'),
        ),
        migrations.AlterField(
            model_name='order',
            name='useage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='产品用途'),
        ),
        migrations.AlterField(
            model_name='order',
            name='useage_detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用途细分'),
        ),
    ]
