# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-25 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180625_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='series_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='产品序列号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='应收总价'),
        ),
    ]
